name: Create pre-release
on:
  workflow_dispatch:
jobs:
  checkout:
    name: Checkout
    runs-on: ubuntu-latest
    steps:
      - name: Checkout RegRepo
        uses: actions/checkout@v2
        if: ${{ !vars.SKIPCHECKOUT || vars.SKIPCHECKOUT == 'false' }}
        with:
          repository: ${{ github.repository }}
          ref: ${{ github.ref }}
          path: repo
